### ISSUE TITLE
TestWaveformGenerator failure on x86_64 macOS

### ISSUE THREAD

**Issue by OPNA2608** [libsidplayfp/libsidplayfp#39]
Since v2.3.0, `TestWaveformGenerator` is crashing in `TestNoiseWriteBack1` on [x86_64 macOS](https://hydra.nixos.org/build/156829227/nixlog/6). [aarch64 macOS](https://hydra.nixos.org/build/161083085/log) seems unaffected and keeps passing just fine.

> ```
> FAIL: TestWaveformGenerator
> ===========================
> 
> TestWaveformGenerator.cpp:89:1: error: Failure in TestNoiseWriteBack1: Unhandled exception: test crashed
> ```

The test worked fine on [v2.2.0](https://hydra.nixos.org/build/155837854/log). I've run the test binary under `lldb` and got the following output:

```
Process 17057 stopped
* thread #1, queue = 'com.apple-main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x3f80)
    frame #0: 0x00000001000067d9 TestWaveformGenerator`reSIDfp::WaveformGenerator::output(this=0x00007ffeefbff460, ringModulator=<unavailable>) at WaveformGenerator.h:403 [opt]
   400  
   401      // DAC imperfactions are emulated by using waveform_output as an index
   402      // into a DAC lookup table. readOSC() uses waveform_output directly.
-> 403      return dac[waveform_output];
   404  }
   405  
   406  } // namespace reSIDfp
Target 0: (TestWaveformGenerator) stopped.
(lldb) bt
* thread #1, queue = 'com.apple-main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x3f80)
  * frame #0: 0x00000001000067d9 TestWaveformGenerator`reSIDfp::WaveformGenerator::output(this=0x00007ffeefbff460, ringModulator=<unavailable>) at WaveformGenerator.h:403 [opt]
    frame #1: 0x000000010000388a TestWaveformGenerator`SuiteWaveformGenerator::TestTestNoiseWriteBack1::RunImpl(this=<unavailable>) const at TestWaveformGenerator.cpp:101 [opt]
    frame #2: 0x0000000100008681 TestWaveformGenerator`void UnitTest::ExecuteTest<UnitTest::Test>(UnitTest::Test&, UnitTest::TestDetails const&, bool) + 97
    frame #3: 0x0000000100009107 TestWaveformGenerator`UnitTest::TestRunner::RunTest(UnitTest::TestResults*, UnitTest::Test*, int) const + 103
    frame #4: 0x0000000100008ddd TestWaveformGenerator`UnitTest::RunAllTests() + 109
    frame #5: 0x00007fff7334a015 libdyld.dylib`start + 1
(lldb)
```

**Comment by drfiemost** [comment]
This was introduced with a466ee2, I wonder why it didn't trigger a CI error...

**Comment by drfiemost** [comment]
Fixed, thanks!
